---
# Perform APT update
- name: Upgrade APT data
  apt: update_cache=yes cache_valid_time=3600
  tags: ubuntu

# Perform APT upgrade
- name: Upgrade APT packages to the latest
  apt: upgrade=safe
  tags: ubuntu

# Remove apparmor - keep linux distro consistency
- name: Remove apparmor in favor of selinux
  apt: state=absent pkg={{ item }}
  with_items:
    - apparmor
    - apparmor-utils
  tags: ubuntu

# Install Web Server
- name: Install Apache on Ubuntu
  package:
    name: apache2
    state: present
  tags: ubuntu

# Enable Web Server at Boot
- name: Enable HTTPD Service [Boot ON]
  service:
    name: apache2
    state: started
    enabled: yes
  tags: ubuntu

# Install Common Utilities
- name: Install Common Utilities
  apt: state=installed pkg={{ item }}
  with_items:
    - htop
    - nano
    - vim
  tags: ubuntu

# Install Common Security Components
- name: Install Common Security Components
  apt: state=installed pkg={{ item }}
  with_items:
    - ufw
    - fail2ban
    - auditd
    - logwatch
    - selinux
    - python-selinux
    - selinux-policy-ubuntu
  tags: ubuntu

# Configure UFW
- import_tasks: ufw.yml
  when: ansible_distribution|lower =="ubuntu"

# Configure selinux
- import_tasks: selinux.yml

# Configure auditd
- import_tasks: auditd.yml

# Move fail2ban config to remote host
- import_tasks: update-configs.yml